# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 430)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 430))
        MainWindow.setMaximumSize(QtCore.QSize(400, 430))
        MainWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        MainWindow.setAcceptDrops(True)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow {\n"
"        background-color: #3d3d3d;\n"
"        border: none;\n"
"        margin: 0px;\n"
"        padding: 0px;\n"
"}")
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(300, 300))
        self.centralwidget.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget {\n"
"        background-color: #071b4a;\n"
"        border: none;\n"
"}")
        self.centralwidget.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(1, 6, 3, 2)
        self.gridLayout.setHorizontalSpacing(8)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.coin2_Edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.coin2_Edit.setMinimumSize(QtCore.QSize(300, 100))
        self.coin2_Edit.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(41)
        self.coin2_Edit.setFont(font)
        self.coin2_Edit.setStyleSheet("QLineEdit {\n"
"        background-color:  #0a276b;\n"
"        /*border: 2px solid #2d2d2d;*/\n"
"        border-radius: 10px;\n"
"} ")
        self.coin2_Edit.setObjectName("coin2_Edit")
        self.gridLayout.addWidget(self.coin2_Edit, 5, 1, 1, 1)
        self.combo_bottom = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_bottom.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.combo_bottom.sizePolicy().hasHeightForWidth())
        self.combo_bottom.setSizePolicy(sizePolicy)
        self.combo_bottom.setMinimumSize(QtCore.QSize(300, 50))
        self.combo_bottom.setMaximumSize(QtCore.QSize(300, 50))
        self.combo_bottom.setToolTipDuration(-1)
        self.combo_bottom.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.combo_bottom.setStyleSheet("QComboBox {\n"
"        background-color: #2098b0;\n"
"        border-radius: 10px;\n"
"        padding: 17px;\n"
"    \n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"        border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(/home/bento/Documents/Linux/python/pyqt5/exchangerate/icons/down_arrow_icon.png);\n"
"    width: 24px;\n"
"    height: 24px;\n"
"    padding-right: 23px;\n"
"}")
        self.combo_bottom.setEditable(False)
        self.combo_bottom.setCurrentText("")
        self.combo_bottom.setMaxVisibleItems(80)
        self.combo_bottom.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.combo_bottom.setObjectName("combo_bottom")
        self.gridLayout.addWidget(self.combo_bottom, 4, 1, 1, 1)
        self.coin1_Edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.coin1_Edit.sizePolicy().hasHeightForWidth())
        self.coin1_Edit.setSizePolicy(sizePolicy)
        self.coin1_Edit.setMinimumSize(QtCore.QSize(300, 100))
        self.coin1_Edit.setMaximumSize(QtCore.QSize(300, 100))
        self.coin1_Edit.setSizeIncrement(QtCore.QSize(20, 20))
        self.coin1_Edit.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.coin1_Edit.setFont(font)
        self.coin1_Edit.setStyleSheet("QLineEdit {\n"
"        background-color:  #0a276b;\n"
"        /*border: 2px solid #2d2d2d;*/\n"
"        border-radius: 10px;\n"
"} ")
        self.coin1_Edit.setObjectName("coin1_Edit")
        self.gridLayout.addWidget(self.coin1_Edit, 2, 1, 1, 1)
        self.combo_top = QtWidgets.QComboBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.combo_top.sizePolicy().hasHeightForWidth())
        self.combo_top.setSizePolicy(sizePolicy)
        self.combo_top.setMinimumSize(QtCore.QSize(300, 50))
        self.combo_top.setMaximumSize(QtCore.QSize(300, 50))
        self.combo_top.setStyleSheet("QComboBox {\n"
"        background-color: #2098b0;\n"
"        border-radius: 10px;\n"
"        padding: 17px;\n"
"    \n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"        border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(/home/bento/Documents/Linux/python/pyqt5/exchangerate/icons/down_arrow_icon.png);\n"
"    width: 24px;\n"
"    height: 24px;\n"
"    padding-right: 23px;\n"
"}")
        self.combo_top.setEditable(False)
        self.combo_top.setCurrentText("")
        self.combo_top.setMaxVisibleItems(80)
        self.combo_top.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.combo_top.setIconSize(QtCore.QSize(16, 16))
        self.combo_top.setObjectName("combo_top")
        self.gridLayout.addWidget(self.combo_top, 1, 1, 1, 1)
        self.flag_top = QtWidgets.QLabel(parent=self.centralwidget)
        self.flag_top.setMinimumSize(QtCore.QSize(80, 65))
        self.flag_top.setMaximumSize(QtCore.QSize(80, 65))
        self.flag_top.setStyleSheet("QLabel {\n"
"    border: 2px solid #2098b0;\n"
"\n"
"}")
        self.flag_top.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.flag_top.setText("")
        self.flag_top.setPixmap(QtGui.QPixmap("country-flags-main/png100px/br.png"))
        self.flag_top.setScaledContents(True)
        self.flag_top.setObjectName("flag_top")
        self.gridLayout.addWidget(self.flag_top, 1, 0, 1, 1)
        self.flag_bottom = QtWidgets.QLabel(parent=self.centralwidget)
        self.flag_bottom.setMinimumSize(QtCore.QSize(80, 65))
        self.flag_bottom.setMaximumSize(QtCore.QSize(80, 60))
        self.flag_bottom.setAutoFillBackground(False)
        self.flag_bottom.setStyleSheet("QLabel {\n"
"    border: 2px solid #2098b0;\n"
"\n"
"}")
        self.flag_bottom.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.flag_bottom.setText("")
        self.flag_bottom.setPixmap(QtGui.QPixmap("country-flags-main/svg/us.svg"))
        self.flag_bottom.setScaledContents(True)
        self.flag_bottom.setObjectName("flag_bottom")
        self.gridLayout.addWidget(self.flag_bottom, 4, 0, 1, 1)
        self.clock_label = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clock_label.sizePolicy().hasHeightForWidth())
        self.clock_label.setSizePolicy(sizePolicy)
        self.clock_label.setMinimumSize(QtCore.QSize(120, 20))
        self.clock_label.setMaximumSize(QtCore.QSize(120, 20))
        self.clock_label.setObjectName("clock_label")
        self.gridLayout.addWidget(self.clock_label, 7, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ExchangeRate"))
        self.clock_label.setText(_translate("MainWindow", "Oct 8 13:45 PM"))
